### ISSUE TITLE
Composition API

### ISSUE THREAD

**Issue by mahouha** [tomosterlund/qalendar#115]
Hello, I saw in documentation that you use optionAPI and I want to know if this package support composition API or not ?

regards.

**Comment by tomosterlund** [comment]
Hello @mahouha. Yes, you can use this component in composition API as well.

To my knowledge, which API is used is a component-internal affair only, meaning the API you use has no effect on which components you can import. I just tried this with:

```vue
<script setup lang="ts">
import { Qalendar } from "qalendar";
</script>

<template>
  <main>
    <Qalendar />
  </main>
</template>

<style>
@import '../node_modules/qalendar/dist/style.css';

main {
  height: 800px;
  width: 90%;
  max-width: 1600px;
}
</style>

```

Thanks for raising this question. I will try to clarify this in the documentation site.
