### ISSUE TITLE
Support for mobile drag/drop 

### ISSUE THREAD

**Issue by shamime** [tomosterlund/qalendar#116]
Sorry if this is not the right place to submit this. I was wondering if there is a roadmap for supporting actions (drag/drop) for mobile devices. I found a reference that it's not currently supported, and since majority of users these days are relying on the mobile device support - decided to ask. Thank you for a great tool!!

**Comment by tomosterlund** [comment]
Thank you for opening this feature request @shamime.

Actually, I've noticed the documentation is not quite up to date here. Drag & Drop is available in month mode for devices with touch events. But I can also look into the technical requirements for implementing drag & drop in week & day modes on mobile. I'll get back to you on this topic.

**Comment by tomosterlund** [comment]
I believe I managed to implement this. I haven't tested it on an authentic touch device, however, but only on desktop Chrome in simulated mobile. Feel free to test it with `npm install qalendar@1.19.0-beta.1`. If you can confirm that this works I will go ahead and graduate that version to 1.19.0, if not, I can also see if I find the time to test it on a proper touch device within the next few weeks.

**Comment by tomosterlund** [comment]
If you run `npm i qalendar@1.19.0-beta.1` you will get a version that supports drag & drop also on mobile. I have one slightly annoying behavior to fix, namely that the scroll container of the day/week is scrolled along with the dragging. This looks a bit ugly, but basically the functionality of dragging events across a day is now in place.

**Comment by shamime** [comment]
@tomosterlund thank you so much for getting back to me, and for implementing this feature!!
I plan to look into it soon - I'm in the middle of upgrading my app to vue 3, and as you can imagine it's not a quick task to complete. I'm very much excited to give a try to qalendar!!

**Comment by tomosterlund** [comment]
Yes, I feel ya. That's not a small task :)

Thanks again for the feature request. This feature is now available on the latest version of the package.
