### ISSUE TITLE
Any indicator for weekend?

### ISSUE THREAD

**Issue by loicgeek** [tomosterlund/qalendar#121]
**Is your feature request related to a problem? Please describe.**
We sometime need to change bg color for weekend,  but currently I see no class for it.

**Comment by tomosterlund** [comment]
That's true. I will try and think of something here. Currently I'm leaning towards simply adding a class for every place where a day is defined, like so: `is-monday`, `is-tuesday` ... `is-saturday`, `is-sunday`. And then let implementers make sure to couple this selector with other selectors such as:

```css
.week-timeline__day.is-saturday {
/* rule */
}
```

or 

```css
.calendar-month__weekday.is-sunday {
/* rule */
}
```

**Comment by loicgeek** [comment]
@tomosterlund  adding a tag to the `dayInterface` would also help, so the. user would decide. by himself what to do if current Day is weekend

**Comment by tomosterlund** [comment]
@loicgeek please describe exactly how you wish that the API should look, if you want to add anything to the config-interface, and also a more precise suggestion for what the possible options and outcomes should be.
