### ISSUE TITLE
Better calendar Month view. design for mobile 

### ISSUE THREAD

**Issue by loicgeek** [tomosterlund/qalendar#131]
**Is your feature request related to a problem? Please describe.**
The current month view of calendar is not very professional

**Describe the solution you'd like**
We may consider show a calendar and. the depending on the day select show events

**Additional context**
![image](https://user-images.githubusercontent.com/33604660/223152035-ed1b6c2d-005e-4cab-98ce-323143972eea.png)

**Comment by tomosterlund** [comment]
I agree, the mobile month view can be improved drastically. One thing that has to be done with high prioprity is to hide the leading and trailing days on mobile. On desktop they are there for symmetry, but here it's just confusing. I'll get on this.

Any other more specific wishes?

**Comment by tomosterlund** [comment]
@loicgeek should we just go for replicating this one?

https://help.syncfusion.com/flutter/calendar/month-view#month-agenda-view

**Comment by tomosterlund** [comment]
Now released with v3.0.0. Thank you so much for your active part in making it happen :)
