### ISSUE TITLE
The returned data should include time when it is the agenda view

### ISSUE THREAD

**Issue by loicgeek** [tomosterlund/qalendar#144]
**Is your feature request related to a problem? Please describe.**
Currently, on agenda view, when you click on a specific time, it only returns. the that, it should also includes time
![image](https://user-images.githubusercontent.com/33604660/226616109-bbc3993c-a54b-4a02-b252-eecff1540a61.png)

**Additional context**
```
    "qalendar": "^2.0.0-beta.1"
```

**Comment by tomosterlund** [comment]
Actually, there is a way to achieve this: https://tomosterlund.github.io/qalendar/guide.html#intervals

Maybe you can try out the `displayClickableInterval` option, and see if this does what you need to do?
