### ISSUE TITLE
Events are not appearing after state change

### ISSUE THREAD

**Issue by Oni22** [tomosterlund/qalendar#168]
**Describe the bug**
I created a very simple test component to test this library and it seems like that the events are not updated when I push a new one. I can see that my stateful array is updating because I was printing it on top of the calendar. Only Qalendar is not reacting to any changes.

**To Reproduce**

1. Follow the Documentation setup
2. Use the composition API and create a stateful variable `const events = ref<any>([])` 
3. pass it to the :events attribute in <Qalendar/>
4. Push a new event to events variable
5. Nothing happens

**Expected behavior**
New event should appear in calendar

**Screenshots**

<img width="1133" alt="Screenshot 2023-05-16 at 11 34 52" src="https://github.com/tomosterlund/qalendar/assets/17254331/8d001966-d346-4777-a223-8da9e76a7677">

**Context:**

- Browser Chrome
- Nuxt3 (3.0.0)
- Qalendar (2.5.0)

**Additional context**
```js
<template>
  <div>
    <ClientOnly>
      {{ events }}
      <Qalendar
        :events="events"
        @day-was-clicked="onDayClicked"
      />
    </ClientOnly>
  </div>
</template>

<script setup lang="ts">
import { Qalendar } from 'qalendar'

const events = ref<any>([])

function onDayClicked(e: any) {
  console.log('DAY', e)

  events.value.push({
    title: 'Advanced algebra',
    with: 'Chandler Bing',
    time: { start: '2023-05-16 08:00', end: '2023-05-16 09:00' },
    color: 'red',
    isEditable: true,

    id: '12',
    description: 'test'
  })
}
</script>

<style>
@import 'qalendar/dist/style.css';
</style>



```

**Comment by tomosterlund** [comment]
Hi @Oni22

Actually until now this library hasn’t exposed any methods or documented recommendations to update events. There are multiple ways to do this, but one way is described by @loicgeek on Discord:

https://discord.com/channels/1084178906036314152/1084923455604006965/1086178547049189376

Since the events prop is not a primitive type, the variable passed needs to be set new, not just updated.

But I realize now maybe I should expose an “addEvents” and a “removeEvents” method, to make it a bit more explicit how to achieve this. I’ll add this to the roadmap, and will close this issue. If you need any further help on this topic, you can write us on Discord

**Comment by ibrahimrehman1** [comment]
Hi @tomosterlund Any updates on this one? Thanks

**Comment by ibrahimrehman1** [comment]
@loicgeek @Oni22 Hi Guys! Can you help me to achieve this? The discord link is not working on my side :(

**Comment by ibrahimrehman1** [comment]
Thanks @loicgeek but unfortunately its not loading on my side. Checked it on mobile as well as laptop. Can you share a screenshot please? Thanks

**Comment by loicgeek** [comment]
Hi <@608688187287797780> , in order for the component to redraw, you have to update a variable, when pushing an object to an array, the actual array is not changed, so you can use spread operator  like this this.events =[...this.events, newobject]

**Comment by ibrahimrehman1** [comment]
Thanks a lot @loicgeek it worked ✔

**Comment by morteza-mortezai** [comment]
> Hi @Oni22
> 
> Actually until now this library hasn’t exposed any methods or documented recommendations to update events. There are multiple ways to do this, but one way is described by @loicgeek on Discord:
> 
> https://discord.com/channels/1084178906036314152/1084923455604006965/1086178547049189376
> 
> Since the events prop is not a primitive type, the variable passed needs to be set new, not just updated.
> 
> But I realize now maybe I should expose an “addEvents” and a “removeEvents” method, to make it a bit more explicit how to achieve this. I’ll add this to the roadmap, and will close this issue. If you need any further help on this topic, you can write us on Discord

discord channel is not working !
