### ISSUE TITLE
Expose methods to go to previous month and next month to developer

### ISSUE THREAD

**Issue by MarcelR1998** [tomosterlund/qalendar#213]
**Is your feature request related to a problem? Please describe.**
I'm building a custom header to control the calendar and would like to access the built-in methods to switch to the previous/next period from custom elements.

**Describe the solution you'd like**
Adding a ref on date picker element and a method to that in turn exposes the goToPeriod method to the top level

**Comment by tomosterlund** [comment]
Accepted and merged with: https://github.com/tomosterlund/qalendar/pull/212
