### ISSUE TITLE
Add "first day of week" to Qalendar options

### ISSUE THREAD

**Issue by josephclaytonhansen** [tomosterlund/qalendar#223]
**Is your feature request related to a problem? Please describe.**
Some cultures or contexts work best with a calendar that starts on Sunday, others work better with Monday. Currently, Qalendar only allows Monday as the start date of the week.

**Describe the solution you'd like**
I would like an option added to `props` that sets a `firstDayOfWeek` property. For example:
```
...
props: {
        events: Array,
        config: {
          defaultMode: 'month',
          firstDayOfWeek: 'sunday'
        }
...
```

Thanks for your consideration

**Comment by josephclaytonhansen** [comment]
I would be happy to add this myself, by the way, if I'm given pull request creation access I'll make a PR for review

**Comment by tomosterlund** [comment]
This feature already exists:

```vue
config: {
  week: {
    startsOn: 'sunday'
  }
}
```

**Comment by josephclaytonhansen** [comment]
Very cool- it doesn't seem to work for me, though: 
<img width="988" alt="Screen Shot 2023-12-11 at 8 59 59 AM" src="https://github.com/tomosterlund/qalendar/assets/45859835/561bf9cf-5d84-4694-a1ff-0bc7917e6f33">
<img width="467" alt="Screen Shot 2023-12-11 at 9 00 56 AM" src="https://github.com/tomosterlund/qalendar/assets/45859835/21e89223-78b7-4500-8cf8-a031d2b41f72">

**Comment by josephclaytonhansen** [comment]
actually, I'm realizing that the config seems to be ignored entirely for me... my code is extremely simple, I double-checked the docs and from what I can tell, it should be working 
<template>
    <div class = "calendar-wrapper">
        <Qalendar 
        :events="events"
        :config="config"
        />
    </div>
</template>

<script>
import { Qalendar } from "qalendar";

export default {
    name: 'VCalendar',
    components: {
        Qalendar
    },
    props: {
        events: Array,
        config: {
          defaultMode: 'month',
          week: {
            startsOn: 'sunday'
          },
        }
    }
}
</script>
```

**Comment by tomosterlund** [comment]
You're declaring config as a prop. You would probably want to declare this as a data property? I believe this is not a correct way to declare props in vue: https://vuejs.org/guide/components/props.html

**Comment by josephclaytonhansen** [comment]
You're entirely right, my apologies for wasting your time with something so silly. Thanks!!

**Comment by tomosterlund** [comment]
Don't worry. Happens to all of us!
