### ISSUE TITLE
[Bug] Event dialog has wrong position when event is on the bottom of viewport

### ISSUE THREAD

**Issue by lukasz-fi** [tomosterlund/qalendar#248]
**Context (REQUIRED):**

- Browser: chrome
- Browserversion: 123.0.6312.107
- Qalendar Version: 3.8.1

**Describe the bug (REQUIRED)**

See screenshot.

**To Reproduce**

1. Go to https://tomosterlund.github.io/qalendar/guide.html
2. Scroll down to Qalendar, so that an event is on the bottom of the screen
3. Click the event.

The event dialog is cut off on the bottom.

**Expected behavior**

The event dialog would start on a position that the whole dialog is visible

**Screenshots**

<img width="969" alt="Screenshot 2024-04-08 at 16 24 45" src="https://github.com/tomosterlund/qalendar/assets/156190621/12988c8c-fa25-466a-809b-4ae8ee1b13dc">

**Additional context**

This problem exists only if the event in on the bottom of a viewport with scroll. If the event in rendered of the bottom of a page then the dialog is positioned correctly.

**Comment by tomosterlund** [comment]
That's true, this is sub-optimal. I'm not sure I consider this a bug though, because the calendar itself is not completely scrolled into view; The modal is only cut off because the calendar itself is.

Will mark this a wont-fix, since I'm not adding enhancements to this library anymore.
