### ISSUE TITLE
Only DAY display

### ISSUE THREAD

**Issue by wotamann** [tomosterlund/qalendar#49]
Thank you for making your excellent Qalendar project!

Today I created a a new **Vue 3.0 (Vite 3.0) Project** with `npm init vue@latest` and then added 'qalendar' via `npm i qalendar `  
and I could only see the 'DAY' Mode and in the top-selection only the day-picker. 

I tried `config = { defaultMode: "month" }` without success

BROWSER:
latest FF or Chrome

CODE:
```
<template>
  <qalendar :events="events" :config="config" />
</template>

<script setup>
import { Qalendar } from "qalendar";
import { ref } from "vue";

const events = ref([
  {
    title: "Advanced algebra",
    with: "Chandler Bing",
    time: { start: "2022-07-22 12:05", end: "2022-07-22 13:35" },
    color: "yellow",
    isEditable: true,
    id: "753944708f0f",
    description: "Lorem ipsum dolor"
  }
]);

const config = ref({
  defaultMode: "month",
  isSilent: false,
});
</script>

<style>
/** Please observe, that your path to the node_modules directory might be different */
@import "../../node_modules/qalendar/dist/style.css";
</style>

```
SCREENSHOT:
![grafik](https://user-images.githubusercontent.com/5354164/180601654-61bc0b7e-8412-4b85-ae0c-50ba913259e9.png)

Please maybe you can help me and explain why it does not work to show 'week' or 'month'.

with best regards in advance

woko

**Comment by tomosterlund** [comment]
Hi @wotamann

First of all, thank you for the appreciation, and for taking the time to open an issue.

From the screenshot it seems like you are wrapping the component in a very thin containing element. For now, only the day mode has an interface compatible with screens that small. And honestly, at the moment I don't have any viable ideas for how to implement other modes on small screens. For that reason the calendar defaults to day mode in your example. In the documentation this is documented in the following comment

> // Please note, that smaller devices can only utilize the day mode

But probably this needs to be documented a little clearer, and be clearer that it's about the width of the wrapping element, and not the device itself.

If you give it a wider containing element, does it work well?

**Comment by wotamann** [comment]
Thank you for your correct advice, that was exactly the problem and it was located in `./asset/main.css`

```
@media (min-width: 1024px) {
  body {
    display: flex;
    place-items: center;
  }

  #app {
    display: grid;
    grid-template-columns: 1fr 1fr;
    padding: 0 2rem;
  }
```
