### ISSUE TITLE
Freely definable intervals in the week/day view

### ISSUE THREAD

**Issue by wotamann** [tomosterlund/qalendar#50]
Thanks again for your great project!

I have a running project with Vuetify 2.6.7 and working with their Calendar element. Unfortunately Vuetify 2.6.7 is not VUE 3 compatible and the next version 3.0 is not only delayed but will no longer support the Calendar element in this form.  While looking for a calendar, your project appealed to me and I liked it very much. 

Our project needs quarter hourly intervals in the week/day overview starting from e.g. 8:00, 8:15 ... to 16h00 ending. We have to to enter events, with a click-event fired when the interval is clicked e.g. 9:15.  The ability to click into an interval and define an event here via the @click:interval would be a feature that might be of interest to others. I think there are a lot of people who have worked with the Vuetify Calendar component and are now facing the problem like me, that this Calendar is no longer supported in the upcoming VUE3 compatible Vuetify version.

The interval props of Vuetify 2.6.7 are shown [here ](https://vuetifyjs.com/en/api/v-calendar-daily/#props) and the calendar [here](https://vuetifyjs.com/en/components/calendars/)

Perhaps you could accept this suggestion as a Feature request.

with best thanks in advance

wotamann

**Comment by tomosterlund** [comment]
Thanks again for your input. I would definitely consider building something that allows you to get the corresponding time to a click in a day. A couple of questions:

1) The way you wish to use it, do the styles of the intervals need to be customizable?
2) The interval props for Vuetify are a bit abstract to me, I don't quite get it. But is this what you want?

- You define intervals to be 15 minutes, for example via an `:interval-length="15"` prop, or in the config object.
- User clicks somewhere in a day, for example 20:14
- Qalendar emits event ```@click:interval``` where the payload would be for example ```2022-07-23 20:00```

**Comment by tomosterlund** [comment]
Or do you wish the intervals to appear optically in some way, on the side of a day?

**Comment by wotamann** [comment]
Each interval should be a separate field, which should be clickable, so that I can then enter a separate event at this point. 

I can give you a screenshot from my project

![grafik](https://user-images.githubusercontent.com/5354164/180615468-51ab3303-f38c-4cd5-a762-fd72519b08af.png)

**Comment by tomosterlund** [comment]
Ok, I like it 👍  I'll do this one as the next feature

**Comment by wotamann** [comment]
THX - That would be really great 👍

**Comment by tomosterlund** [comment]
I committed a few things yesterday, and now only need to catch up on writing some tests for it.

If you want to try it out and see if the feature works like you would expect, I can leave the branch open until you had the chance to try it out. Getting up and running for testing it should be pretty quick. All you'd need to do after forking would be:

- `npm i`
- `husky install`
- `npm run seed`
- `npm run dev`

And in the file `development/QalendarView.vue` there is a configuration option called `dayIntervals` that you could play around with. If you then open the console and click around on the intervals, you would see the output that would be emitted.

**Comment by tomosterlund** [comment]
And if you don't have the time/chance to check it out, I'll just do some clean-up work and then try and make a new release during the week :)

**Comment by wotamann** [comment]
**Great and thank you for your efforts**, I checked the branch and it works! 

It's now possible to insert a new Event, by clicking into the 15min Time-Interval-Field and push the new event to events[]. 

> The interval props for Vuetify are a bit abstract to me, I don't quite get it. 

If it would be ok for you, this could be a proposal for implementing interval-props

```
dayIntervals: {
    first-interval: 32, //  The first interval to display in the day view. 
    // If intervalMinutes is set to 15 and this is set to 32 x 15 
    // the first time in the view is 8h/8am  (32 x 15min = 8hours)

    interval-minutes: 15, // The number of minutes the intervals are in the day view. 
    // A common interval is 60 minutes so the intervals are an hour.

    interval-count: 40, // The number of intervals to display in the day view. 
    // in this case 8h plus 40 x 15min = 10hours -> display ends with 18h/6pm 

    interval-format: null, // Function to format time of day string that appears 
    // in the interval gutter of the day and week view to specified locale

    interval-height: 50, // The height of an interval in pixels in the day view.

    interval-style: { color: '#0F0' },   // Object or Function returning CSS-Style
}
```
... and if you want to give the user full control over the look of event and interval, then implementing an additional Slot for each `event` and `interval` could be a good option.
 
```
<Qalendar
    :config="config"
    :events="events"
    @event-was-clicked="reactToEvent"
    @interval-was-clicked="handleIntervalWasClicked"
>

    <template v-slot:event="event" >
        <strong>{{ev.title}}</strong>
    </template>

    <template v-slot:interval="interval>
        <span >{{interval.startTime}}</span>
    </template>

</Qalendar>
```

**Comment by tomosterlund** [comment]
Release 1.5.0 now contains the feature of defining clickable intervals. Docs for the feature can be found here: https://tomosterlund.github.io/qalendar/#intervals

I can picture building a feature with the `intervalCount`, `intervalFormat` and `firstInterval` options within the next few weeks.

The last feature suggestion, for giving full control over the looks of events and intervals, also sounds desirable. However, I don't really have an idea for how I would build it. If you could picture building at least parts of the feature, pull requests are more than welcome, and I could also support where needed.

**Comment by tomosterlund** [comment]
@wotamann Just wanted to let you know, version 1.6.0, released today, comes with the ability to define custom events through slots: https://tomosterlund.github.io/qalendar/#custom-events
