### ISSUE TITLE
Open calendar card when allready clicked away

### ISSUE THREAD

**Issue by felix-berlin** [tomosterlund/qalendar#51]
![image](https://user-images.githubusercontent.com/17964384/180615238-99fcd6a9-a872-454b-b405-e7451edffec0.png)

_For documentation purposes, because within the projects kanban board no pictures can be uploaded._

**To Reproduce**
Click on a calendar entry then navigate thou the docs.

**Comment by tomosterlund** [comment]
Here is the PR, if you would like to test the branch :)

https://github.com/tomosterlund/qalendar/pull/55
