### ISSUE TITLE
pt-BR language

### ISSUE THREAD

**Issue by rayanneblima** [tomosterlund/qalendar#76]
Hey! Thanks for this project.

I'm using this one and I need to configure it for Brazilian Portuguese (pt-BR).

So I made some changes but I don't have permission on the project:

**keys.ts**
`
export const languageKeys = {
  /** The following three keys, describe the calendar modes */
  week: {
    "it-IT": "Settimana",
    "en-US": "Week",
    "de-DE": "Woche",
    "sv-SE": "Vecka",
    "zh-CN": "周",
    "pt-BR": "Semana",
  },
  month: {
    "it-IT": "Mese",
    "en-US": "Month",
    "de-DE": "Monat",
    "sv-SE": "Månad",
    "zh-CN": "月",
    "pt-BR": "Mês",
  },
  day: {
    "it-IT": "Giorno",
    "en-US": "Day",
    "de-DE": "Tag",
    "sv-SE": "Dag",
    "zh-CN": "日",
    "pt-BR": "Dia",
  },

  /** Other keys */
  moreEvents: {
    "it-IT": "+ altri eventi",
    "en-US": "+ more events",
    "de-DE": "+ weitere Ereignisse",
    "sv-SE": "+ fler händelser",
    "zh-CN": "列出其他结果",
    "pt-BR": "+ mais eventos",
  },
};
`

**index.ts**
`
import { languageKeys } from "./keys";

export default {
  data() {
    return {
      languageKeys,
    };
  },

  methods: {
    getLanguage(languageKeys: any, locale: string) {
      if (locale.startsWith("de")) locale = "de-DE";
      if (locale.startsWith("en")) locale = "en-US";
      if (locale.startsWith("it")) locale = "it-IT";
      if (locale.startsWith("sv")) locale = "sv-SE";
      if (locale.startsWith("zh")) locale = "zh-CN";
      if (locale.includes("BR")) locale = "pt-BR";

      return languageKeys[locale]
        ? languageKeys[locale]
        : languageKeys["en-US"] || "";
    },
  },
};
`

**Devtools.vue**
`
 <select id="locale" v-model="locale" name="locale">
        <option value="en-US">en-US</option>
        <option value="de-DE">de-DE</option>
        <option value="sv-SE">sv-SE</option>
        <option value="ja-JP">ja-JP</option>
        <option value="ru-RU">ru-RU</option>
        <option value="zh-CN">zh-CN</option>
        <option value="pt-BR">pt-BR</option>
</select>
`

Could I send the changes in a Pull Request or could you apply the codes above, please?

**Comment by tomosterlund** [comment]
Hey there,

Thanks for taking the time to open this issue.

You should be able to open a pull request for this repo, if you first click on "Fork", then create your own Fork of the repo. After you committed and pushed to your own fork (which is then a separate repository under your account), you should be able to open a pull request. This is also the standard way of opening pull requests for open source projects on Github :)

If you want I can add the changes above too, but that way you're not automatically accredited as a contributor to the library. Let me know if you need any help

**Comment by rayanneblima** [comment]
Thanks for the information, I will proceed in this way then to send the feature :rocket:

**Comment by tomosterlund** [comment]
Cool.

I updated the Contributor's guide here: https://github.com/tomosterlund/qalendar/blob/master/.github/contributing.md#committing since the project uses commitlint for consistent commit messages. I had forgotten to document this until now
