### ISSUE TITLE
[Emitted events] day-was-clicked

### ISSUE THREAD

**Issue by MaximSedov** [tomosterlund/qalendar#84]
Hi! Thank you for your work!
Is it possible to add event, after an **day** in the calendar was clicked?

**Comment by tomosterlund** [comment]
Hi Maxim. Actually, there is a config-option which allows you to click somewhere in a day, and get a timestamp emitted. The option is `dayIntervals.displayClickableInterval`, and once you've set this to true, you can listen for events with `@interval-was-clicked`.

Let me know if this is what you pictured, or if you need something else.

**Comment by MaximSedov** [comment]
> Hi Maxim. Actually, there is a config-option which allows you to click somewhere in a day, and get a timestamp emitted. The option is `dayIntervals.displayClickableInterval`, and once you've set this to true, you can listen for events with `@interval-was-clicked`.
> 
> Let me know if this is what you pictured, or if you need something else.

Great!
But what about when month-by-month mode is active (I would like to get a day)? In this case, the event does not occur

**Comment by tomosterlund** [comment]
Right, that's a good point. In month mode there would be no elegant way of doing that right now. I added this to the road-map, and could try and make it happen this weekend, when we hopefully roll out a couple of other planned features anyway: https://github.com/tomosterlund/qalendar/projects/1#card-86583378

Thank you for your contribution :)

**Comment by tomosterlund** [comment]
Hello again. This feature is now available in version [1.11.0](https://github.com/tomosterlund/qalendar/releases/tag/v1.11.0).

It is also documented here: https://tomosterlund.github.io/qalendar/#emitted-events

**Comment by MaximSedov** [comment]
Beautiful! Thank you so much!
