### ISSUE TITLE
Can't start with qalendar ! 

### ISSUE THREAD

**Issue by mahouha** [tomosterlund/qalendar#88]
Hellow, I appreciate this package and really I need it,
I run vue 3 project with vite@3.1.8,
 I install this package and I try to test the package but I have one error and many warnings, I don't if there is incompatibility of versions
![error](https://user-images.githubusercontent.com/25373754/201346556-c24ec3a3-4506-4847-9332-3904b564fd43.JPG)
![warning](https://user-images.githubusercontent.com/25373754/201346581-c6d0bf65-bf0b-4306-a9ba-1ee877b5772e.JPG)

**Comment by felix-berlin** [comment]
Hi @mahouha, I'm glad you like Qalendar.

Are you using the options-API or the composition API?
Do you use SFC (Single-File Components) in your project?

**Comment by mahouha** [comment]
I test it using options-API like docs,  and Yes I use SFC and composition API in my project
```
<template>
    <Qalendar :events="events" />
</template>

<script>
import {Qalendar} from "qalendar";
export default {
    components: {
        Qalendar,
    },
    data() {
        return {
            events: [
                // ...
                {
                  title: "Advanced algebra",
                  with: "Chandler Bing",
                  time: { start: "2022-05-16 12:05", end: "2022-05-16 13:35" },
                  color: "yellow",
                  isEditable: true,
                  id: "753944708f0f",
                  description: "..."
                },
            ],
        }
    },
}
</script>
```

**Comment by felix-berlin** [comment]
Can you please share all your dependencies, dev dependencies and Node version?

Even better would be of course an example on Stackblitz ect. 😊

**Comment by mahouha** [comment]
- node v16.15.0
- npm 8.5.5

```
"dependencies": {
    "@headlessui/vue": "^1.7.4",
    "@popperjs/core": "^2.11.6",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "pinia": "^2.0.23",
    "qalendar": "^1.10.0",
    "vue": "^3.2.41",
    "vue-router": "^4.1.5",
    "vue-slider-component": "^4.1.0-beta.6"
  },
  "devDependencies": {
    "@mdi/js": "^7.0.96",
    "@rushstack/eslint-patch": "^1.1.4",
    "@tailwindcss/forms": "^0.5.3",
    "@vitejs/plugin-vue": "^3.1.2",
    "@vue/eslint-config-prettier": "^7.0.0",
    "autoprefixer": "^10.4.13",
    "eslint": "^8.22.0",
    "eslint-plugin-vue": "^9.3.0",
    "postcss": "^8.4.18",
    "prettier": "^2.7.1",
    "sass": "^1.56.0",
    "tailwindcss": "^3.2.1",
    "vite": "^3.1.8"
  }
```

**Comment by mahouha** [comment]
in Stakblitz it run successfuly [https://stackblitz.com/edit/vue-4jhryn?file=package.json](url) 
I don't know why in localhost it wan't runing :(

**Comment by felix-berlin** [comment]
@mahouha  Were you able to find out what the problem was? If so, I would set the issue to close.
