### ISSUE TITLE
Scroll to 0 not working

### ISSUE THREAD

**Issue by maha-oueghlani** [tomosterlund/qalendar#92]
**Describe the bug**
the scroll option can't work with hour 00:00 
when I try to scroll to 0 it scrolls to 8H

**To Reproduce**
```
 config: {
      ...
        week: {
           startsOn: "monday",
         ...
          // Scroll to a certain hour on mounting a week. Takes any value from 0 to 23.
          scrollToHour: 0,
        },
     ...
}
```

**Expected behavior**
Scrolling to 00:00 onmounted

**Context:**

- Browser :  Chrome Version 107.0.5304.107
- Browser : Firefox version 106

**Comment by tomosterlund** [comment]
This is now fixed in version 1.10.1

Thanks again for taking the time to report the bug.
