### ISSUE TITLE
Resetting the display mode when the window changes

### ISSUE THREAD

**Issue by MaximSedov** [tomosterlund/qalendar#97]
Hi! It's me again, sorry for the intrusion :)

There is such a situation: if calendar is opened in a mode, which is not set in config as "defaultMode", then at the slightest change of window size - the mode is reset to the value in config (although it is not necessary to), and we see such a jump, as on the video.

Besides, it seems to me, that we should add "emit" (the same as @updated-mode) for just such a situation, which will inform us, that the mode of display has changed at increase/decrease of window size (not only by clicking on modes menu).

Thanks!

https://user-images.githubusercontent.com/41785330/202534529-72d9b241-be79-4619-9bf0-14659df28f1d.mp4

**Comment by tomosterlund** [comment]
Hi. Thanks for taking the time again!

This is definitely a bug. But I think the appropriate behavior would be that it doesn't change modes on resizing, except when it reaches the breakpoint where only day mode can be shown. I won't have the time to fix it this week. I could probably get to it sometime next week, but if you want to fix it before, you can also open a pull request.

I'm fairly certain that the cause of this lies somewhere in the top level component `[Qalendar.vue](https://github.com/tomosterlund/qalendar/blob/master/src/Qalendar.vue)`

**Comment by tomosterlund** [comment]
Managed to find it and fix it now. In release 1.12.1 this should not occur anymore.

Thanks again for reporting!

**Comment by MaximSedov** [comment]
Thank you so much for another quick fix!
