### ISSUE TITLE
Possibility not to disable month view on small screens

### ISSUE THREAD

**Issue by MaximSedov** [tomosterlund/qalendar#99]
Hi, are there any plans to allow calendar view by month on small screens? For example, shifting the columns(cell) to the next line or horizontal scrolling?

Thanks!!!

**Comment by tomosterlund** [comment]
Hello Maxim,

Thank you for this feature request. I agree that this would be a good feature to have, and it probably wouldn't be too complicated. Just like you say, we would probably just need to adjust some flex behavior.

Right now, however, I don't have a ton of time for new features. Would you be interested in forking the repo and build this feature yourself?

If not I'll just add it to the road map and get on it when I have time.

**Comment by MaximSedov** [comment]
Okay, I hear you! I'll be glad to see it on the road map :)

**Comment by tomosterlund** [comment]
Found some time for this on the weekend anyway :) 

This feature is now available in version [1.14.0](https://github.com/tomosterlund/qalendar/releases/tag/v1.14.0)

**Comment by MaximSedov** [comment]
Very cool! Thank you so much!
